### ISSUE TITLE
add option to align latent positions to positive orthant

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#154]
have an option to rotate embedding s.t. the entries are in the positive orthant, truncate ones that aren't, and then plot everything on a log-log scale

**Comment by bdpedigo** [comment]
@alyakin314 I think this is different from medflips into first orthant. just looking for any orthogonal transformation s.t. as many nodes as possible live in the first orthant. I have found this useful for plotting and tutorials. wonder if there are any hacky heuristics, like procrustes to a matrix that consists of points along `y = x` in the first orthant or some other "dummy matrix" in the first orthant

**Comment by alyakin314** [comment]
> @alyakin314 I think this is different from medflips into first orthant. just looking for any orthogonal transformation s.t. as many nodes as possible live in the first orthant. I have found this useful for plotting and tutorials. wonder if there are any hacky heuristics, like procrustes to a matrix that consists of points along `y = x` in the first orthant or some other "dummy matrix" in the first orthant

interesting problem. my gut feeling also was to somehow exploit the `x=y` line. this is only a proxy, of course, but since procrustes minimizes Frobenius norm, this is vaguely similar to least squares, so the solutions should favor that bring more points to this line, rather than some points really closely and ignore others (i.e. it should _not_ favor sparse solutions, which is good). but this needs to actually be tested.

this is actually more similar to bringing to sign flips first orthant than one may think, because they both can likely be accomplished by just using our existing 2-sample align methods with a dummy matrix (for sign flips it is just `I_d`).
