### ISSUE TITLE
bring oos stuff

### ISSUE THREAD

**Issue by jovo** [microsoft/graspologic#161]
- https://github.com/neurodata/primitives-interfaces/tree/master/jhu_primitives/oosase
- https://github.com/neurodata/primitives-interfaces/tree/master/jhu_primitives/ooslse
- https://github.com/neurodata/primitives-interfaces/tree/master/jhu_primitives/oosgmm

oosgmm could just be an option in gclust

the other two, it would be desirable to run some experiments evaluating the pro's/con's of sparse vs oos

**Comment by hhelm10** [comment]
@j1c and i talked about oosase and decided to add predict method to ase.

given adjacency matrix, A in (n, n)
and 
m out of sample adjacency vectors, X in (m, n):

ASE = AdjacenecySpectralEmbed()
in_sample_embedding = ASE.fit_transform(A)
X = (m, n) array 
oos_embedding = ASE.predict(X)

**Comment by loftusa** [comment]
is there a paper or some more info associated with this?

**Comment by bdpedigo** [comment]
i think this https://arxiv.org/pdf/1802.06307.pdf and I think we want the LLS version. some code linked above

**Comment by bdpedigo** [comment]
really amounts to [this line](https://github.com/neurodata/primitives-interfaces/blob/d2773136a7dc30777c9b90c0dd8bcd0be12b167e/jhu_primitives/oosase/oosase.py#L248) which uses the pseudoinverse but I think is faster then `pinv` in numpy

**Comment by loftusa** [comment]
dope, I'm tentatively thinking I want to work on this

**Comment by bdpedigo** [comment]
cool. IMO there's a lot of thinking to do w.r.t what interface makes the most sense here

**Comment by loftusa** [comment]
#162

**Comment by loftusa** [comment]
DoD:
- recreate figure 1 from oos paper to demonstrate successful implementation
- plan for API, discussed with @bdpedigo before implementation
- implementation of API PR'd
- tests (open to suggestions/changes)
    - is oos embedding almost always within an acceptable range of ground-truth embedding? (define "acceptable")
    - do independent OOS embeddings cluster harder around ground truth embedding as number of vertices increases?
    - does the least-squares implementation satisfy the moore-penrose conditions for pseudoinverse?
    - other tests will probably pop up as API is planned out

**Comment by loftusa** [comment]
use cases
- an original graph is too big, so we want to make a signal subgraph and embed it, then find the latent positions for the rest of the nodes with oos
- we have a graph and embed it normally. Later, we get a new (maybe way bigger) graph that we're pretty sure was generated from the same underlying distribution, and we use oos embedding because it's easier computationally
- (maybe specific instance of second case) we have two graphs for which there is a partial one-to-one correspondence between vertices, and we know that partial correspondence -- but some vertices don't have known buddies. We omnibus embed a subgraph with only corresponding vertices, and use oos to embed the rest.

(any more?)

I'm thinking the best way to find an API that works well is to literally just simulate these use cases and play around with API implementation ideas until I'm able to do it in a way that feels simple and clean.

the other benefit of this approach is that the notebooks that come out could eventually become tutorials.

**Comment by bdpedigo** [comment]
The third one I mentioned is probably not worth fretting about right now, though I do want it someday probably. But requires OOS Omni which I think is out of scope for this issue

**Comment by loftusa** [comment]
@bdpedigo @hhelm10  can I get a better sense on here of what the problems you guys ran into re: clunkiness with the last iteration of the API in #162?

**Comment by hhelm10** [comment]
i think the clunkiness came from over-fitting the implementation to a specific application. if you are designing it and dont run into clunkiness concerns then i wouldnt be alarmed.

**Comment by bdpedigo** [comment]
@loftusa if you don't plan on doing all of these, can you open issues for 
- Out of sample LSE
- Out of sample Omni (and maybe MASE? not sure)

**Comment by loftusa** [comment]
> @loftusa if you don't plan on doing all of these, can you open issues for
> 
> * Out of sample LSE
> * Out of sample Omni (and maybe MASE? not sure)

#544 #545
