### ISSUE TITLE
UnmatchedTest tutorial should be on an unmatched example

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#177]
I don't like how the exact same example I used for the MatchedTest tutorial was used for Unmatched also. We should:
- [ ] explain when one would use unmatched
- [ ] generate an example where the two graphs are not matched and use that for the tutorial
- [ ] make sure all plots have axes labels

**Comment by bdpedigo** [comment]
@bvarjavand

**Comment by bdpedigo** [comment]
once #222  is done we can do this

**Comment by alyakin314** [comment]
i can do this also when pr'ing size fix, if you want
@bdpedigo @bvarjavand

**Comment by bdpedigo** [comment]
That would be great!

**Comment by alyakin314** [comment]
i feel like it makes most sense to only do this after #375 ?

cc: @bdpedigo

**Comment by bdpedigo** [comment]
@alyakin314 either order makes sense to me, up to you if you wanna do it

**Comment by alyakin314** [comment]
@bdpedigo don't really mind delegating this to ndd as well (and would be happy to consult whoever will take this).

**Comment by bdpedigo** [comment]
@kareef928 wanna do this one too? We finally have the tools to do so... I think you'd be able to do this issue and the other I tagged you in this semester

**Comment by kareef928** [comment]
I'd be down to do this too

**Comment by kareef928** [comment]
Dod: Modifications to the latent distribution test tutorial will be made so that the following will be included:

- An explanation of when to use the latent distribution test over the latent position test

- Examples of the latent distribution test being used on two unmatched graphs (m /= n) in the cases we expect the null hypothesis to be true and false - generate labeled figures of null distribution, test statistic, p-value for both cases
