### ISSUE TITLE
Include all options for `palette` in docs.

### ISSUE THREAD

**Issue by MrAE** [microsoft/graspologic#317]
## Expected Behavior
A complete list of options for the palette argument should appear in the docs, i.e. `Set1`, ..., `muted`, ...?

## Actual Behavior
>`palette:str, dict, optional, default: 'Set1'`
>Set of colors for mapping the hue variable. If a dict, keys should be values in the hue variable.

**Comment by j1c** [comment]
Perhaps a link to matplotlib's list of qualitative cmaps? e.g. https://matplotlib.org/3.1.3/tutorials/colors/colormaps.html#qualitative

**Comment by bdpedigo** [comment]
second what @j1c says

**Comment by MrAE** [comment]
That'd suffice.

**Comment by Jingyan230** [comment]
Does this issue still need help? Maybe I can try to deal with it. But I'm not sure I understand the mission...

**Comment by bdpedigo** [comment]
@Jingyan230 there are some places in the documentation for our plotting functions (like [here](https://github.com/neurodata/graspy/blob/ca4001315b2d00d19437609afa6bdf96577fd7ce/graspy/plot/plot.py#L417)) where we tell the user there is an argument called `palette`. The suggestion here is to add [this link](https://matplotlib.org/3.1.3/tutorials/colors/colormaps.html#choosing-colormaps-in-matplotlib) to the description of that argument, so that users have an easier time figuring out what the valid arguments are. Hope that helps?

**Comment by Jingyan230** [comment]
Thanks. I'll have a try.
