### ISSUE TITLE
Write tutorials for clustering functions

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#333]
We currently don't have tutorial notebooks for these, would be nice to have a brief notebook or two explaining their usage. Could talk to @tathey1 for examples from his paper, potentially.

**Comment by caseypw** [comment]
I'll get this done this semester

**Comment by caseypw** [comment]
> I'll get this done this semester

I can finish this as my sprint 1 for this semester, unless it would be more prudent to work on something else @bdpedigo

**Comment by kareef928** [comment]
I am also interested in this issue

**Comment by bdpedigo** [comment]
assigning this one to @caseypw cause he actually already did some work on this last semester

**Comment by caseypw** [comment]
**DoD:** PR with new tutorial notebook for clustering functions as well as other file changes necessary for the documentation

**Comment by bdpedigo** [comment]
@caseypw thanks for commenting with some DoD info. I'm going to ask everyone to do this in a week or two. 

For your DoD, I'd like more info. For example, can you sketch out what kind of simulations/results/metrics you'd like to have at a high level?

**Comment by caseypw** [comment]
# Clustering Tutorial
### [Gclust](https://arxiv.org/abs/1909.02688)
- Explain Gaussian Mixture Model
   - Math from Section 2.1 in [paper](https://arxiv.org/abs/1909.02688) included in introduction and mathematics paragraph in markdown in notebook, explains all parameters
- Before each tutorial, explanatory paragraph in markdown describing why parameters are chosen and why they have specific default values.
- **Simulations**
   - Data identical to simulated data in [paper](https://arxiv.org/abs/1909.02688): section 3.1.1
   - Tutorial Run 1: Default
     - `{min, max}_components` both set to default
     - `covariance_type`: 'all'
     - `tol`: 1e-3
     - `reg_covar`: 1e-6
     - `max_iter`: 100
     - `n_init`: 1
     - `init_params`: 'kmeans'
     - `random_state`: None
   - Tutorial Run 2: Random
     - `{min, max}_components` both set to default
     - `covariance_type`: 'all'
     - `tol`: 1e-3
     - `reg_covar`: 1e-6
     - `max_iter`: 100
     - `n_init`: 1
     - `init_params`: 'random'
     - `random_state`: None
   - Can also include these runs, but up to @bdpedigo @j1c :
     - With different `max_iter` value, discuss runtime effects of increasing this value
     - With different `{min, max}_components`
- **Metrics/Results**
   - Either comparable to paper and explain what was explained in paper
   - Or explain differences (method used, parameters, etc)

### [AutoGMM](https://arxiv.org/abs/1909.02688)
- Explain Automated Gaussian Mixture Model
   - Math from Section 2.1 in [paper](https://arxiv.org/abs/1909.02688) included in introduction and mathematics paragraph in markdown in notebook, explains all parameters and describes agglomerative clustering, mentions `gclust` tutorial notebook for reference.
- Before each tutorial, explanatory paragraph in markdown describing why parameters are chosen. Also explain why `max_components` is defaulted to 10 in `autogmm` but has no default value in `gclust`. Explain difference in function structure between `autogmm` and `gclust`.
- **Simulations**
   - Data identical to simulated data in [paper](https://arxiv.org/abs/1909.02688): section 3.1.1
   - Tutorial Run 1: In-depth (verbose) default
     - `{min, max}_components` both set to default
     - `affinity`: 'all'
     - `linkage`: 'all'
     - `covariance_type`: 'all'
     - `random_state`: None
     - `label_init`: None
     - `max_iter`: None
     - `selection_criteria`: "bic"
     - `verbose`: 2
     - `max_agglom_size`: 2000
     - `n_jobs`: None
   - Tutorial Run 2: In-depth AIC
     - `{min, max}_components` both set to default
     - `affinity`: 'all'
     - `linkage`: 'all'
     - `covariance_type`: 'all'
     - `random_state`: None
     - `label_init`: None
     - `max_iter`: None
     - `selection_criteria`: "aic"
     - `verbose`: 2
     - `max_agglom_size`: 2000
     - `n_jobs`: None
  - Can also include these runs: 
    - Non in-depth versions of the same previous runs
    - {In, Not in}-depth with different `max_iter` value
    - {In, Not in}-depth with different `{min, max}_components`
    - {In, Not in}-depth with `label_init`
    - {In, Not in}-depth with higher `max_agglom_size`, discuss runtime effects of increasing this value
- **Metrics/Results**
   - Either comparable to paper and explain what was explained in paper
   - Or explain differences (method used, parameters, etc)

### [Kclust](https://arxiv.org/abs/1909.02688)
- Explain Kmeans Cluster
   - Math from Section 2.1 in [paper](https://arxiv.org/abs/1909.02688) included in introduction and mathematics paragraph in markdown in notebook, explains all parameters, describes difference from other clustering algorithms.
- Before each tutorial, explanatory paragraph in markdown describing why parameters are chosen. Explain difference in function structure from `autogmm` and `gclust`.
- **Simulations**
   - Data identical to simulated data in [paper](https://arxiv.org/abs/1909.02688): section 3.1.1
   - Tutorial Run 1: Default
     - `max_clusters`: 1
     - `random_state`: None
   - Tutorial Run 2: Higher max cluster
     - `max_clusters`: 2
     - `random_state`: None
- **Metrics/Results**
   - Either comparable to paper and explain what was explained in paper
   - Or explain differences (method used, parameters, etc)
- Simulations for kclust can have different simulated data since paper mainly focuses on Gaussian Mixture Modeling
