### ISSUE TITLE
remove * import in simulations

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#334]
https://github.com/neurodata/graspy/blob/master/graspy/simulations/__init__.py

should not be using * import here

**Comment by kareef928** [comment]
I can do this one

**Comment by dwaynepryce** [comment]
I'd urge you guys to not use star imports at all.  They can be fine if you have an explicit `__all__` but if you guys do a `dir(module.path.name.thing.here)` on some things you can often see a lot of private functions and whatnot being pulled in.

I believe iPython and thus Jupyter (if you have code completion) turned on makes heavy use of dir() - and I'm not sure whether vscode or intellij/pycharm do as well, but in general I try to keep everything in `dir()` as something I want the user to see - and thus am responsible for.  I mean, I can't stop them from actually calling a private-ish thing because Python :tm: but not returning it in dir() is just one more signal that you should keep your mitts off it.

I'm pretty opinionated on this but it _is_ an opinion, so feel free to contradict me!

**Comment by loftusa** [comment]
> I'd urge you guys to not use star imports at all. They can be fine if you have an explicit `__all__` but if you guys do a `dir(module.path.name.thing.here)` on some things you can often see a lot of private functions and whatnot being pulled in.
> 
> I believe iPython and thus Jupyter (if you have code completion) turned on makes heavy use of dir() - and I'm not sure whether vscode or intellij/pycharm do as well, but in general I try to keep everything in `dir()` as something I want the user to see - and thus am responsible for. I mean, I can't stop them from actually calling a private-ish thing because Python ™️ but not returning it in dir() is just one more signal that you should keep your mitts off it.
> 
> I'm pretty opinionated on this but it _is_ an opinion, so feel free to contradict me!

this came up pretty heavily yesterday: https://github.com/microsoft/graspologic/pull/431#discussion_r489872615

**Comment by bdpedigo** [comment]
> I'd urge you guys to not use star imports at all. They can be fine if you have an explicit `__all__` but if you guys do a `dir(module.path.name.thing.here)` on some things you can often see a lot of private functions and whatnot being pulled in.
> 
> I believe iPython and thus Jupyter (if you have code completion) turned on makes heavy use of dir() - and I'm not sure whether vscode or intellij/pycharm do as well, but in general I try to keep everything in `dir()` as something I want the user to see - and thus am responsible for. I mean, I can't stop them from actually calling a private-ish thing because Python ™️ but not returning it in dir() is just one more signal that you should keep your mitts off it.
> 
> I'm pretty opinionated on this but it _is_ an opinion, so feel free to contradict me!

We agree, that was the goal of this issue and #461
