### ISSUE TITLE
Documentation Questions: contributing.rst

### ISSUE THREAD

**Issue by daxpryce** [microsoft/graspologic#480]
I'm updating all the naming stuff now (at least in a first pass), and I'm taking note of some of the places where the graspy approach differs from the topologic approach. I am registering issues at each of these places so we can have a conversation about what our actual approach should be going forward and how best to execute a merger.

In this specific placeholder issue, I'm wanting to talk about the contributing.rst file.  We def. don't want duplicates, so the question is: do we link to the github MD file, or does Github link to the contributing.html file we publish @ ReadTheDocs?

**Comment by dwaynepryce** [comment]
Note: I made an immediate executive decision to err on the side of linking to the Github one for now mostly because I don't want to try to spruce up the RST to match what the MD currently says.  I'll do it later if we decide to, but renaming is already a PITA and I don't want this PR to be the size of a small space station.

**Comment by bdpedigo** [comment]
I'm learning towards Github one linking to whatever we host on RTD

Only reason being I just looked and that's what sklearn, pandas, scipy all do, seems like a fine convention. Also in case we ever make that file more extensive (like the ones for those packages) it'd be nice to have it generated with all the same tools as the docs, as there are often code examples, etc.
