### ISSUE TITLE
matching test is unstable because of directory path

### ISSUE THREAD

**Issue by alyakin314** [microsoft/graspologic#507]
running `pytest` when in tests directory breaks because this path

https://github.com/microsoft/graspologic/blob/b9547d80c056de342db85b0d3238e43b110f07be/tests/match/test_match.py#L64

isn't true.

**Comment by dwaynepryce** [comment]
`os.path.join` would fix this rather neatly

**Comment by asaadeldin11** [comment]
With regard to this issue, I think there is some pretty inefficient stuff in the match tests at the moment. Right now, the whole qap library is being stored in `qapdata` (~20 .dat files) , but I've recently changed the tests to only use one of these matrix pairs. I propose deleting this `qapdata` folder which is storing a lot unused things, and just making the single example I am using in my test file, since it's only a 12x12 matrix anyway. This will solve the path issue, and also get rid of unused data. Thoughts?

**Comment by bdpedigo** [comment]
im fer it

**Comment by asaadeldin11** [comment]
this leaves only one file in the `tests/match` folder, so I'm going to get rid of that and just have `test_match.py` directly in the tests folder.
