### ISSUE TITLE
simplify readme to look like scipy

### ISSUE THREAD

**Issue by sampan501** [microsoft/graspologic#511]
readme's, in my opinion, should be simple (like [scipy](https://github.com/scipy/scipy)) and route traffic to docs

**Comment by alyakin314** [comment]
not a strong opinion on this, but i disagree. i kind of like when readme has a tl;dr of how to use/install. although readmes have mutated from something that just comes with software on a disk to being presented on the main page of the software repositories, i always thought of readme files as something that contains the minimal information i need to have to run the thing, rather than a menu. i.e. when i just want to install the package, i don't want to click around links and use search engines, i want that to be in readme because that's the one thing they asked me to read before trying to install their software.

**Comment by alyakin314** [comment]
but again, not a very strong opinion, since clicking one link isn't that major of a task to ask either.

**Comment by bdpedigo** [comment]
I do like in scipy how the top is simple and links to several important places. Right now we already try to do that but some of the info is not in the docs which we were discussing on https://github.com/microsoft/graspologic/issues/479 

I don't really see an issue with having more information later down in the readme like in https://github.com/scikit-learn/scikit-learn though.

**Comment by dwaynepryce** [comment]
Something we need to keep in mind is some of our readme is required by Microsoft's OSS office.  They also strongly push us toward conveying a lot of information via the README, though as far as I can tell that last bit is more guidance than Microsoft law

**Comment by bdpedigo** [comment]
![image](https://user-images.githubusercontent.com/25714207/95518819-df86e680-0991-11eb-8da7-dd54544d01bf.png)
