### ISSUE TITLE
Graspologic vs Sk-Network Embedding

### ISSUE THREAD

**Issue by asaadeldin11** [microsoft/graspologic#579]
Benchmark and compare our embedding functionality with that of [sk-network](https://scikit-network.readthedocs.io/en/latest/tutorials/embedding/index.html).

See if one is better than the other in terms of performance/runtime.

Specifically their Spectral/SVD with our LSE/ASE (respectively)

**Comment by dfrancisco1998** [comment]
interested!

**Comment by dfrancisco1998** [comment]
DoD draft: 

Performing something similar to that in the ASE embedding tutorial  "clustering in the embedding space".

For comparing ASE and SVD efficacy:
make an adj matrix using SBM
then using the same num components test SVD and ASE fit
Follow same error analysis at varying number of components on the same adj matrix  and then also with varying insularity
This could be accomplished by recreating the graspologic tutorial using the sk-network SVD mainly because we trust ASE tutorial. 

For runtime, use adj matrix you decide to use for efficacy, just choose a set of vertex sizes and plot node vs time with a line for each us and them

For comparing LSE and Spectral efficacy:
I will follow the same procedure for doing the graspologic tutorial adopted for LSE, which does not involve much change in the original change. 
I will then recreate the sk-network Spectral in the same format of the graspologic  doing the same error analysis as described in the remake of the LSE which follows ASE tutorial. 

The runtime analysis for LSE and Specrtal will follow the same format above.

**Comment by bdpedigo** [comment]
main thing is just runtime. 

then, may want to look at svd approximation error. doubt the clustering stuff will be necessary unless we see big differences. 

also just want to make sure we understand which of their tools match which of ours

**Comment by kareef928** [comment]
I'd be interested in this issue

**Comment by kareef928** [comment]
Sim setting:

Sim 1: SVD vs ASE

1. n_verts = [10, 100, 1000, 10000]
2. Generate an ER graph with n_vert vertices
3. Perform ASE and SVD on the graph (with same n_components) and save the runtimes for each
4. Repeat step 3 for 30 trials
5. Repeat steps 3-4 per n_vert in n_vertices
6. Plot stripplots for times vs n_verts for ASE and SVD

Sim 2: Spectral vs LSE
Exact same process as sim 1 except use spectral instead of SVD and LSE instead of ASE

**Comment by bdpedigo** [comment]
for this i wouldnt worry about multiple runs of each embedding on the same graph. yes, there will be some variance in how long it takes to run even on the same data, but i dont think it'll be huge, and i would rather use that compute time on running 30x more graphs for example. 

how are you timing everything (what commands from what libraries)? 

also, note that runtime will vary depending on input datatype. for now, please use graphs that start as sparse arrays (scipy csr_matrix)

**Comment by kareef928** [comment]
@bdpedigo I'm having trouble with my simulation: particularly in step 5 in the sim setting above. Since the size of the 2D arrays of the true latent positions and the latent positions from ASE/SVD are different, I'm getting an error when I try to do the frobenius norm on them. What should I do about this?

**Comment by bdpedigo** [comment]
why are they different? should set the mto be the same by making the ASE embed into the true number of components

**Comment by kareef928** [comment]
[https://nbviewer.jupyter.org/github/kareef928/graspologic-personal/blob/main/notebooks/norm-test.ipynb](url)

This is a quick notebook of what I'm trying to do; in the last block I'm trying to make ASE embed into the true number of components but I get an error doing so, I'm not sure what I'm doing wrong

**Comment by bdpedigo** [comment]
@kareef928 thanks for posting the notebook. I think what would help us both the most is if you could write out the math of what model you are trying to sample from, and then we can evaluate if your code is doing that. 

(hint: how many nodes are in the graph you are trying to sample, and how many latent dimensions are in the model?)

**Comment by kareef928** [comment]
@bdpedigo went through the rdpg tutorial and now I understand that the dimension of each vector (d) has to be lower than the number of vectors (n). For example, if I was sampling from np.random.uniform(low=0.1, high=1, size=(5, 2)), then I would set n_components=2 in ASE when I do ASE on the rdpg. I made a change to step 2 in my plan so now I sample from uniform distributions of size nx4, could you confirm that this is what we want?

**Comment by bdpedigo** [comment]
Exactly! In theory, the dimension needs to be <= the number of nodes. In practice, depending on the algorithm for doing the SVD that you use, it may need to be <= number of nodes - 1. In general, it will likely be << the number of nodes, otherwise using ASE in general is probably a bad idea. 

So, yes, next steps sound good. Though I believe Jovo said set d=1 and just embed into d=1, which also seems fine. I don't feel too strongly.

**Comment by kareef928** [comment]
https://nbviewer.jupyter.org/github/kareef928/graspologic-personal/blob/main/notebooks/spectral-svd-csr.ipynb

@bdpedigo This is a notebook showing the errors I run into when I try to use csr_matrix in the simulation. Should I make note of these errors in the simulation notebook, or is there a way I can use csr_matrix without running into these errors?

**Comment by bdpedigo** [comment]
why is the input here (5, 4) instead of (5,5)?

**Comment by bdpedigo** [comment]
ASE for any type expects an `n x n` matrix

**Comment by kareef928** [comment]
I do 5x5 later in the notebook but I still get errors when trying to run ASE

**Comment by bdpedigo** [comment]
```pytb
~/Desktop/Graspy_Workspace/graspologic/graspologic/embed/svd.py in selectSVD(X, n_components, n_elbows, algorithm, n_iter)
    257     if (algorithm in ["truncated", "randomized"]) & (n_components >= min(X.shape)):
    258         msg = "n_components must be strictly < min(X.shape)."
--> 259         raise ValueError(msg)
    260     elif algorithm == "truncated":
    261         U, D, V = scipy.sparse.linalg.svds(X, k=n_components)

ValueError: n_components must be strictly < min(X.shape).
```

Notice what the error message for that one is saying - unless you set `algorithm = `full`` then you need to make sure `n_components` is < `n`

**Comment by kareef928** [comment]
https://nbviewer.jupyter.org/github/kareef928/graspologic-personal/blob/main/notebooks/spectral-svd-csr-sim.ipynb

Here is the notebook of applying the embedding methods on a csr_matrix instead of on an RDPG. Should I also PR this notebook into neurodata notebooks, or should I leave a link to the nbviewer version of this notebook in my current PR?

**Comment by bdpedigo** [comment]
could you add to the same notebook you are already PRing?
