### ISSUE TITLE
Cleaner function names

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#586]
There are some common functions that I think could have better names. I'm not a huge fan of shortening commonly-used names when slightly longer names would bring a lot more clarity. Pandas does stuff like `pd.read_clipboard`, for instance, rather than `read_clip`.

Here is a short, non-comprehensive list of functions that I think could be improved with name changes (though I can go through and expand if we decide this is worth doing):
- `utils.to_laplace` > `to_laplacian`
- `utils.get_lcc` > `largest_connected_component` (debatable, maybe `largest_cc`? maybe just `lcc` would be fine here)
- `utils.get_multigraph_union_lcc` and `utils.get_multigraph_intersect_lcc` > `multigraph_lcc` with a keyword argument for union vs intersect
- `utils.cartprod` > `cartesian_product`

**Comment by rajpratyush** [comment]
Hi All, I would like to work on this issue if this is still open.

**Comment by bdpedigo** [comment]
@rajpratyush still open, yes that would be great! Do you need any more info from us?

**Comment by rajpratyush** [comment]
yes @bdpedigo I would like to know what files needs to be changed as I don't have much experience regarding opensource, but I am willing to learn and move ahead in this journey. I would really appreciate some guidance from you as well.
Many thanks,

**Comment by bdpedigo** [comment]
Sounds good @rajpratyush - what is your familiarity with open source thus far (e.g. git, github, making a PR, etc)?

**Comment by bdpedigo** [comment]
With regard to the actual changes that need to be made, all of the functions that @loftusa mentioned are in this file: https://github.com/microsoft/graspologic/blob/dev/graspologic/utils/utils.py. @loftusa any other functions that you think should be changed?

You will need to change:
- the name of the function in the function signature
- the name of the function wherever else it appears in the library
- the name of the function in the corresponding documentation
- the name of the function in any tutorials, if applicable (I don't think any of these functions get called in the tutorials but I could be wrong). The tutorials live [here](https://github.com/microsoft/graspologic/tree/dev/docs/tutorials)

I would recommend trying to use some sort of IDE with a variable naming tool (VS code, for instance) because many of those tools can change a function name throughout the entire library for you. If not, then something like find and replace, but again, would have to make sure to check other files in the library.

**Comment by rajpratyush** [comment]
I know all the basic git commands know how to use github creating an issue and making a PR , FORK, pushing to remote repository. The experience i lack i am deficient of is of working on large codebases @bdpedigo

**Comment by rajpratyush** [comment]
Sure sir i will start my work on it tommorrow itself @bdpedigo  will keep you posted regarding the progress i have made.
