### ISSUE TITLE
[BUG] seaborn `distplot` soon-to-be-depracated

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#594]
we use `sns.distplot` [internally](https://github.com/microsoft/graspologic/blob/dev/graspologic/plot/plot.py#L674) in our plotting functions

distplot is [depracated](https://seaborn.pydata.org/generated/seaborn.distplot.html) in the newest version of seaborn

**Comment by bdpedigo** [comment]
@j1c @loftusa @alyakin314 @dwaynepryce @asaadeldin11 is anyone opposed to specifying `seaborn >= 0.11`? Because the function `distplot` was basically renamed to `histplot` we either have to pick one (i assume we'd pick the more recent version) or have some code that checks `sns.__version__` and picks the right function name based on that. I'm in favor of just migrating to most recent seaborn.

**Comment by loftusa** [comment]
@bdpedigo I'm in favor, opens up access to the new functionality in that version and I think staying on top of most-updated dependencies is probably good practice in general

**Comment by dwaynepryce** [comment]
Let's just update

**Comment by alyakin314** [comment]
agreed with ^

**Comment by bdpedigo** [comment]
Closed by #541
