### ISSUE TITLE
Remove requirements from README.md

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#625]
I propose we at least remove the dependencies listed on the readme since they are very likely to get out of date as we add/remove dependencies (they currently are incorrect).

I personally don't feel like we need to replace them with anything. If we really want this somewhere, the only thing I can think of is somehow to make the docs load this up to date info from setup.py, but that feels like overkill to me.

Related to #511, which we could also do instead.

**Comment by bdpedigo** [comment]
Any thoughts @dwaynepryce @Nyecarr @asaadeldin11 @alyakin314 @j1c @loftusa

**Comment by dwaynepryce** [comment]
I only like non-requirement dependencies/preconditions/whatever to be listed - things like OS or any system level packages we might need (for instance, tkinter to display renderings of a graph layout natively). Things that you would `apt install` or `brew install` or whatever - those things make sense. I'm always looking in setup.py or requirements.txt for my stuff on *any* project anyway presuming that's the ground truth and the documentation is a lie, because that's usually how it is - and we have a great example of that right now! :D

**Comment by j1c** [comment]
Fine with me. You can see it as it updates here as well (https://github.com/microsoft/graspologic/network/dependencies)

**Comment by rajpratyush** [comment]
Hi all, I like to contribute to this issue if  this issue still open ??

**Comment by bdpedigo** [comment]
Hi @rajpratyush - thanks for your interest! You are welcome to work on this one, do you need any info from us?

**Comment by rajpratyush** [comment]
Yes, can you guide me lil bit as I was highly impressed by your idea of automatic updating of dependencies in case they are depreciated or updated. I am highly interested in working on this idea.

**Comment by bdpedigo** [comment]
> Yes, can you guide me lil bit as I was highly impressed by your idea of automatic updating of dependencies in case they are depreciated or updated. I am highly interested in working on this idea. @bdpedigo

Appreciate the enthusiasm, but I think for now we just want to remove the dependencies section from the README file here https://github.com/microsoft/graspologic/blob/dev/README.md#python-dependencies

**Comment by rajpratyush** [comment]
Sure sir, I will do it and submit a PR tommorrow itself

**Comment by rajpratyush** [comment]
Please check if the changes made are correct @bdpedigo
