### ISSUE TITLE
documentation organization

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#665]
[why are the tutorials flat now in the sidebar?](https://microsoft.github.io/graspologic/tutorials/index.html)
(feels less organized)

also, there's no way at first glance to get back to the documentation home page when you're in the tutorials section. 

It also redirects to an entirely different site from homepage>tutorials (readthedocs.io > microsoft.github.io/).

**Comment by dwaynepryce** [comment]
Tutorials and reference docs are different beasts now.  One gets published to readthedocs, the other gets published to github.

There's no real good way to get GH pages to do versioning of reference docs and tutorials all in one fell swoop like RTD does, and tutorial generation fails on read the docs because it has resource limits we're really close to running afoul of (memory constraints of 3gb, 15m total runtime).  

So.. these are going to be split, on purpose, by design. Consistency is still good, so whatever you think you can do to make it more consistent I am thoroughly for.  As for tutorial flattening, there was a good reason for it but if it also horks up the sidebar then it isn't good enough imo, so feel free to revert that change!  Not sure why I didn't notice it before.

**Comment by loftusa** [comment]
I think the biggest issue atm is that if you're [here](https://microsoft.github.io/graspologic/tutorials/index.html), I don't think there's a way to get back to the homepage?

**Comment by rajpratyush** [comment]
even though we have a home icon but I think it should be enlarged and then added a hyperlink to the icon

**Comment by bdpedigo** [comment]
> As for tutorial flattening, there was a good reason for it but if it also horks up the sidebar then it isn't good enough imo, so feel free to revert that change! Not sure why I didn't notice it before.

I agree w/ @loftusa about the old organization, @dwaynepryce are you saying you know exactly how to revert that organization to what it was?

**Comment by loftusa** [comment]
Closed due to overlap with #720
