### ISSUE TITLE
[BUG] Two conf.py files

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#707]
why is there a conf.py file both

[here](https://github.com/microsoft/graspologic/blob/dev/docs/reference/conf.py)
and 
[here](https://github.com/microsoft/graspologic/blob/dev/docs/tutorials/conf.py)

cause I think it's causing issues with my pytest?
<img width="1238" alt="Screen Shot 2021-02-13 at 5 56 46 PM" src="https://user-images.githubusercontent.com/12386450/107863767-e84a6600-6e24-11eb-8678-bc75f2e9e201.png">

**Comment by rajpratyush** [comment]
@loftusa now As you have mentioned of When I was about to merge my first commit Ben suggested me to use black at that time I had also ran this pytest and  it had gave me a lot of errors which had been in my my since. so what kind of fix do you suggest for this? will renaming and then finding what other files use the conf.py of tutorial section and modifying it as well work?

**Comment by loftusa** [comment]
> @rajpratyush

I'm not sure. In my local branch I just deleted one of the `conf.py` files (since there are two) and it fixed my pytest. I'm not sure if deleting one of them would cause issues in the main branch. Maybe @dwaynepryce or @bdpedigo knows?

**Comment by dwaynepryce** [comment]
I would simply suggest not calling `pytest` from the root.  If you want to call exactly what the github actions call, take a look at the commands in `Makefile` in the root: https://github.com/microsoft/graspologic/blob/dev/Makefile#L14
