### ISSUE TITLE
Make netlify build status report not required to merge

### ISSUE THREAD

**Issue by bdpedigo** [microsoft/graspologic#712]
## Is your feature request related to a problem? Please describe.
Would like to keep the netlify build from blocking a merge cause it can take a while for status to be reported and we are already building the docs via github anyway

## Additional context
Don't think I am able to modify these settings (i did see anything as part of our workflows so i figured this was just a github setting). Maybe something only @dwaynepryce can do?

**Comment by rajpratyush** [comment]
@bdpedigo  I think this article might help
 https://docs.netlify.com/site-deploys/overview/#branch-deploy-controls

**Comment by rajpratyush** [comment]
@bdpedigo Correct me if wrong but I guess we have some like
`deploy/netlify   Expected -- waiting for the status to be reported message`

and this is already a required for building the docs and since it takes time we are not able to merge the PR by then.


I have found a similar issues  answered on netlify support page do check them if it helps out 

https://answers.netlify.com/t/netlify-deployment-stuck-at-expected-waiting-for-status-to-be-reported/15779

https://answers.netlify.com/t/github-commit-status-for-deploy-netlify-doesnt-report-successful/6739

https://answers.netlify.com/t/issues-with-building-pull-request-deploy-previews/14278

**Comment by bdpedigo** [comment]
closing as fixed by @dwaynepryce
