### ISSUE TITLE
Require python >=3.8?

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#717]
I want to be able to use [assignment expressions](https://www.python.org/dev/peps/pep-0572/)  and [positional-only parameters](https://www.python.org/dev/peps/pep-0570/) in my code  
I don't think I can safely if we still support python<3.8? Or is that wrong?

**Comment by bdpedigo** [comment]
personally I'm against this, 3.7 seems pretty widely used still and these seem like relatively small reasons to switch

**Comment by rajpratyush** [comment]
@loftusa there is no way we can use assignment expressions and positional only arguments in python 3.7 because there is no `__future__` import for assignment expressions in Python 3.7 – and adding one in a micro (or "bugfix") release is prohibited by **PEP 6**:

> Prohibitions
> 
> Bug fix releases are required to adhere to the following restrictions:
> There must be zero syntax changes. All .pyc and .pyo files must work (no regeneration needed) with all bugfix releases forked off from a major release.

> Applicability of Prohibitions
> 
> The above prohibitions and not-quite-prohibitions apply both for a final release to a bugfix release (for instance, 2.4 to 2.4.1) and for one bugfix release to the next in a series (for instance 2.4.1 to 2.4.2).

Since assignment expressions constitute a change to the syntax of Python, there's no way they can be added to a future 3.7.x release of Python without breaking this prohibition.

since the python 3.7 support will end on 27 Jun 2023 I don't think switching to python 3.8 is of required now 
as per the website
https://endoflife.date/python

Although in case I think we can create a branch for 3.8 but then it will have its own set of issues and bugs which needs to be rectified and maintenance of both branches will be difficult

**Comment by dwaynepryce** [comment]
To add to more frustration, I'm loathe to say we should admit support for 3.9 since the numba->llvmlite chain only has binary wheels built for up to 3.8.  There are sdists that should work for 3.9, but that opens a can of "this is how you build for python 3.9 on windows / mac / linux" instructions and I swear they change every single time. 

Put another way, if we said >= 3.8, we'd also have to be == 3.8, because 3.9 is still not something our library ecosystem supports as zero-effort install process.  There's always going to be people at the edges who are happy to go the extra mile, but I don't think we need to rush this, even if I deeply approve of all these new restrictions python is finally giving me 👯

**Comment by bdpedigo** [comment]
I motion to close this for now, any objections?

**Comment by bdpedigo** [comment]
happy to reopen if someone has good reason to 😄
