### ISSUE TITLE
[BUG] Using layout_umap and getting key error

### ISSUE THREAD

**Issue by dfrancisco1998** [microsoft/graspologic#738]
## Expected Behavior
a graph layout using UMAP for dim reduction to 2d

## Actual Behavior
coming from layouts\auto.py
 KeyError: '2'

## Example Code
Please see [How to create a Minimal, Reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for some guidance on creating the best possible example of the problem
```python
import networkx as nx
from graspologic.layouts import layout_umap

g = nx.erdos_renyi_graph(10, 0.7, directed=False)
layout_umap(g)
```

## Full Traceback
```pytb
Paste the full traceback in case there is an exception

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-17-1c062a6ca19a> in <module>
      3 
      4 g = nx.erdos_renyi_graph(10, 0.7, directed=False)
----> 5 layout_umap(g)

~\miniconda3\lib\site-packages\graspologic\layouts\auto.py in layout_umap(graph, min_dist, n_neighbors, max_edges, random_seed)
    177         min_dist=min_dist, n_neighbors=n_neighbors, random_state=random_seed
    178     ).fit_transform(tensors)
--> 179     positions = _node_positions_from(lcc_graph, labels, points, random_seed=random_seed)
    180     return lcc_graph, positions
    181 

~\miniconda3\lib\site-packages\graspologic\layouts\auto.py in _node_positions_from(graph, labels, down_projection_2d, random_seed)
    241     scaled_points = _scale_points(down_projection_2d, covered_area)
    242     partitions = leiden(graph, random_seed=random_seed)
--> 243     positions = [
    244         NodePosition(
    245             node_id=key,

~\miniconda3\lib\site-packages\graspologic\layouts\auto.py in <listcomp>(.0)
    246             x=scaled_points[index][0],
    247             y=scaled_points[index][1],
--> 248             size=sizes[key],
    249             community=partitions[key],
    250         )

KeyError: '2'

```

## Your Environment
* Python version:  3.8
* graspologic version:

**Comment by dwaynepryce** [comment]
The core problem going on here is a bit complicated but also very simple at the same time - the TLDR is that we need to ensure we are always treating our keys as str(key) when we do these lookups because `leiden` is 100% of the time going to give you the string representation of your node back as the ID - which is what gets put into the partitions dictionary.  I had no interest trying to get Python's "pass any type of node id you want of any type" thing working in Rust so I just forced everything to encode as a string, which is great when the calling graph's nodes are strings too, but apparently has some issues in auto.py where it's using the original node ID (as an `int`, in this case) as the lookup to generate our `size` dictionary, but using str(node_id) as the key it's looking up with - which isn't going to appear in the sizes dict.

We just need to be careful that any dicts we create in this process are based on a `str(node_id)` or else we'll get things like this.

There's a similar typing issue in `leiden` and `modularity` where we implicitly cast your provided graph as `str(node_id)` for you to be nice and helpful when you call leiden, return `str(node_id) -> partition_id` mappings from leiden, and then when you try to call modularity on it to see how it turned out, it explodes because the graph you provide has `int(node_id)` keys and you're trying to look up `str(node_id)` mappings.

All of this is to say that maybe the right fix is for the python wrapper to our rust native impl should capture the node type in Python, let it cast to string for Rust and Leiden to process it, then before we hand the partition dictionary back we re-cast back to the original type.  And if we purposefully kept the original -> new mapping in memory in Python, we don't even have to have a lossy "cast back", since we'd just replace the new string representation of it back with the original as it was.

And that's the short explanation.

**Comment by bdpedigo** [comment]
> All of this is to say that maybe the right fix is for the python wrapper to our rust native impl should capture the node type in Python, let it cast to string for Rust and Leiden to process it, then before we hand the partition dictionary back we re-cast back to the original type. And if we purposefully kept the original -> new mapping in memory in Python, we don't even have to have a lossy "cast back", since we'd just replace the new string representation of it back with the original as it was.

Big +1 for this, since I definitely think we should allow int or other datatypes as node keys, and this seems like the cleanest/simplest way to allow this.

**Comment by dwaynepryce** [comment]
It would also fix up our modularity bug calculation too, because the types would be what you'd have expected coming back.  So that's probably the right approach

**Comment by dwaynepryce** [comment]
@bdpedigo blech - we generate the edge list that leiden requires in `utils.py` where we generate a `List[Tuple[str, str, float]]`.  That's reasonable as a utility, but I think a `Tuple[Dict[str, Any], List[Tuple[str, str, float]]]` is not really something the common person is going to want - but it is what I need to do to fix this.

So the question is whether I can just axe this from utils or not.  There's benefits to having a "given a graph give me a basic edge list" but for all I know there's like 15 different versions of that behavior already.  So I figured I'd bring it up with you and see if you have a preference for what we do; axe it from utils or give everyone the `Tuple[Dict[str, Any], List[Tuple[str, str, float]]]` return type, which... doesn't seem super useful.  Or, I guess, replicate the function and have a private leiden specific version that does that.

**Comment by bdpedigo** [comment]
hmmm i guess i dont see why the conversion to edgelist needs to be exposed to the user? am i missing something?

> Or, I guess, replicate the function and have a private leiden specific version that does that.

Is this you suggesting we don't need the user to see/care about what leiden is really eating under the hood? If so I agree with that.

**Comment by dwaynepryce** [comment]
We only exposed it before because having a quick way to write out an edge list regardless of what your current graph is was useful for us - sure it only saves like 2 lines of code, but a penny saved is a penny earned or something.  I don't know.

Regardless, it's currently in utils, and changing it to the new way is going to make it less obviously useful, so I'd rather remove it from utils entirely rather than say "here's this wacky function that almost nobody in the world is going to care about now but I guess you can use it to turn a graph in csr matrix form into an edge list if you want as long as you throw half of the top level tuple away" just doesn't sound particularly useful

**Comment by bdpedigo** [comment]
totally fine with removing it from utils, personally!

**Comment by dwaynepryce** [comment]
Augh this shouldn't have been closed
