### ISSUE TITLE
remove mypi check?

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#749]
I vote we take off the mypi check until we implement mypi, so that we can see the little green checkmark again. I miss the little green checkmark. @dwaynepryce thoughts?

**Comment by dwaynepryce** [comment]
I strongly disagree - we're going to talk about it today at the meeting if you can make it - but if anything we need to enable all the type checking so you can see how many things are missed.

In the type hint PR I mentioned how much a struggle it is for me to type hint much of the code that came with graspy, because our methods and functions often have a broad range of argument types and no single, concrete return type depending on what was provided.  That alone isn't the main problem, so much as "I can't tell what anything is when the variable names are only single letters pulled right from the mathematics notation used in the papers that means nothing at all to a software developer".  Basically, it went from "yeah, I can do that!" to "this is an intractable nightmare!"

Anyway, my suggestion is to instead turn it from "fail over dumb stuff" to "fail over the stuff that matters", which I have done in the type-hint PR, but I can also move the configs over separate of the PR so they can at least be failing with actionable, useful information now.

**Comment by loftusa** [comment]
On board with this - closing!
