### ISSUE TITLE
Ensure Python 3.9 and 3.10 compliance

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#771]
Similar to #277. Maybe want to split into separate issues.

**Comment by madlad33** [comment]
Hello, I would Like to contribute to this project and this particular issue.

**Comment by loftusa** [comment]
@madlad33
> Hello, I would Like to contribute to this project and this particular issue.

Excellent! See #471 for the PR that added python 3.8 compliance (although that one is likely much, much bigger than what we need) and #277 for more discussion when we added 3.8 compliance.

You'll also need to add 3.9 (and potentially 3.10) to the set of environments we test on.

@bdpedigo @dwaynepryce do you agree with the above? Anything else you want to add?

**Comment by bdpedigo** [comment]
Yes, I'd just add that the PR/issue you linked were concerned with a lot (I mean A LOT) of other stuff so I don't want @madlad33 to get bogged down by those details. 

Seems like the main first step is just installing graspologic locally in a 3.9 and 3.10 environment, and try to 1) run all our tests and 2) build all our tutorials, then we can go from there. If you have questions about how to do either, perhaps @loftusa can help you/we can update our contributing guidelines to make it more clear. Thoughts @loftusa?

**Comment by loftusa** [comment]
@bdpedigo Sounds good to me!

**Comment by madlad33** [comment]
@loftusa 
>
> Also, welcome, happy to have you!
> 
Thank you, I'm really happy to contribute.

@bdpedigo 
> Yes, I'd just add that the PR/issue you linked were concerned with a lot (I mean A LOT) of other stuff so I don't want @madlad33 to get bogged down by those details.
> 
> Seems like the main first step is just installing graspologic locally in a 3.9 and 3.10 environment, and try to 1) run all our tests and 2) build all our tutorials, then we can go from there. If you have questions about how to do either, perhaps @loftusa can help you/we can update our contributing guidelines to make it more clear. Thoughts @loftusa?

Sure, I will start by running all the tests in 3.9 and 3.10 and then build all the tutorials.

**Comment by dwaynepryce** [comment]
This is not a good first issue;

Somewhere in our dependency chain, we use numba, which needs llvmlite... but there are no binary wheels being built for llvmlite on Python3.9 or Python3.10.  

Not the end of the world if you can compile from sdist, but it's _not_ a low friction process.  If we get this to work we're going to have to have instructions for all 3 OSes, and they should be fresh installs so it's as painful as possible to work through all the kinks :|

**Comment by loftusa** [comment]
> This is not a good first issue;
> 
> Somewhere in our dependency chain, we use numba, which needs llvmlite... but there are no binary wheels being built for llvmlite on Python3.9 or Python3.10.
> 
> Not the end of the world if you can compile from sdist, but it's _not_ a low friction process. If we get this to work we're going to have to have instructions for all 3 OSes, and they should be fresh installs so it's as painful as possible to work through all the kinks :|

https://www.youtube.com/watch?v=8Xt1kUK71lc

**Comment by madlad33** [comment]
> This is not a good first issue;
> 
> Somewhere in our dependency chain, we use numba, which needs llvmlite... but there are no binary wheels being built for llvmlite on Python3.9 or Python3.10.
> 
> Not the end of the world if you can compile from sdist, but it's _not_ a low friction process. If we get this to work we're going to have to have instructions for all 3 OSes, and they should be fresh installs so it's as painful as possible to work through all the kinks :|
@dwaynepryce @loftusa @bdpedigo 
Even if it's not a good first issue, can I still try? It might not be a smooth process, but I can try if you guys allow and guide me. But I can't give instructions for all OSes, I don't have a Mac. I can try to give instructions for Linux and Windows.

**Comment by loftusa** [comment]
> > This is not a good first issue;
> > Somewhere in our dependency chain, we use numba, which needs llvmlite... but there are no binary wheels being built for llvmlite on Python3.9 or Python3.10.
> > Not the end of the world if you can compile from sdist, but it's _not_ a low friction process. If we get this to work we're going to have to have instructions for all 3 OSes, and they should be fresh installs so it's as painful as possible to work through all the kinks :|
> 
> @dwaynepryce @loftusa @bdpedigo
> Even if it's not a good first issue, can I still try? It might not be a smooth process, but I can try if you guys allow and guide me. But I can't give instructions for all OSes, I don't have a Mac. I can try to give instructions for Linux and Windows.

Sure!

**Comment by dwaynepryce** [comment]
What @loftusa said!

I don't want to stop you, I just don't want you to get discouraged OR think it's simple.  One of the problems we run into sometimes is having a fully ready-to-go, all dependencies already installed dev system, and things Just Work for us... and then we find out a fresh OS is dead in the water, because they didn't install some C++ build tool or another.  It's just super frustrating to verify, you know?

But it still has to be done, so you doing it just makes me like 10x happier than me having to do it :D

**Comment by madlad33** [comment]
> This is not a good first issue;
> 
> Somewhere in our dependency chain, we use numba, which needs llvmlite... but there are no binary wheels being built for llvmlite on Python3.9 or Python3.10.
> 
> Not the end of the world if you can compile from sdist, but it's _not_ a low friction process. If we get this to work we're going to have to have instructions for all 3 OSes, and they should be fresh installs so it's as painful as possible to work through all the kinks :|
>
@dwaynepryce
Please correct me If I'm wrong, [here](https://github.com/numba/llvmlite/issues/669 ) it has been mentioned that llvmlite wheels for Python 3.9 have become available with the 0.36.0 release.  

> 
> I don't want to stop you, I just don't want you to get discouraged OR think it's simple. One of the problems we run into sometimes is having a fully ready-to-go, all dependencies already installed dev system, and things Just Work for us... and then we find out a fresh OS is dead in the water, because they didn't install some C++ build tool or another. It's just super frustrating to verify, you know?
> 
How do I get started with the verification?

> But it still has to be done, so you doing it just makes me like 10x happier than me having to do it :D
>
I'm more than happy to contribute :)

**Comment by dwaynepryce** [comment]
> Please correct me If I'm wrong, here it has been mentioned that llvmlite wheels for Python 3.9 have become available with the 0.36.0 release.

Awesome!  Seems to have become valid 29 days ago.

So yeah, I guess the best way to test is to create a venv for 3.9, install the requirements.txt and then run `make test`.

If you run into any issues with `graspologic-native` just let me know - we have at least been building for 3.9!

I haven't bothered building it for 3.10 so that one may be more involved, but I'm willing to change the build matrix and see if it works.  I didn't make it a priority since 3.9 + numba was not happening a few months ago, so I figured 3.10 was right out.

**Comment by madlad33** [comment]
>
> So yeah, I guess the best way to test is to create a venv for 3.9, install the requirements.txt and then run `make test`.
> 
> If you run into any issues with `graspologic-native` just let me know - we have at least been building for 3.9!
> 
> I haven't bothered building it for 3.10 so that one may be more involved, but I'm willing to change the build matrix and see if it works. I didn't make it a priority since 3.9 + numba was not happening a few months ago, so I figured 3.10 was right out.
>
- I created a new venv for 3.9. Got few errors while installing the requirements.txt. 
>
Error 1:
Obtaining file:///L:/Django%20projects/graspologic (from -r requirements.txt (line 1))
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Collecting gensim<=3.9.0,>=3.8.0
  Using cached gensim-3.8.3.tar.gz (23.4 MB)
Collecting POT>=0.7.0
  Using cached POT-0.7.0.tar.gz (189 kB)
    ERROR: Command errored out with exit status 1:
     command: 'l:\django projects\graspologic\venv_2\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\91968\\AppData\\Local\\Temp\
\pip-install-uylcvq96\\pot_69abf993b3004868b2cd1bc42b4e9bb3\\setup.py'"'"'; __file__='"'"'C:\\Users\\91968\\AppData\\Local\\Temp\\pip-install-uylcvq96\\pot_69abf993b3004
868b2cd1bc42b4e9bb3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, _
_file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\91968\AppData\Local\Temp\pip-pip-egg-info-x8x2v3ku'
         cwd: C:\Users\91968\AppData\Local\Temp\pip-install-uylcvq96\pot_69abf993b3004868b2cd1bc42b4e9bb3\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\91968\AppData\Local\Temp\pip-install-uylcvq96\pot_69abf993b3004868b2cd1bc42b4e9bb3\setup.py", line 7, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a8/5d/e7525ff865040845bfacbca4416610761a07db67ba77f6be4e26dd2583bf/POT-0.7.0.tar.gz#sha256=d4ac2bc8791f049a31
66820d51e218d6c299885449b735eafef8d18c76d4ad06 (from https://pypi.org/simple/pot/). Command errored out with exit status 1: python setup.py egg_info Check the logs for f
ull command output.
ERROR: Could not find a version that satisfies the requirement POT>=0.7.0 (from graspologic[dev])
ERROR: No matching distribution found for POT>=0.7.0

ERROR 2:
(venv_2) L:\Django projects\graspologic>pip install -r requirements.txt
Obtaining file:///L:/Django%20projects/graspologic (from -r requirements.txt (line 1))
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Collecting joblib>=0.17.0
  Using cached joblib-1.0.1-py3-none-any.whl (303 kB)
Collecting scikit-learn>=0.22.0
  Using cached scikit_learn-0.24.1-cp39-cp39-win_amd64.whl (6.9 MB)
Collecting numpy>=1.8.1
  Using cached numpy-1.20.2-cp39-cp39-win_amd64.whl (13.7 MB)
Collecting anytree>=2.8.0
  Using cached anytree-2.8.0-py2.py3-none-any.whl (41 kB)
Collecting graspologic-native
  Using cached graspologic_native-0.1.0-cp39-none-win_amd64.whl (187 kB)
Collecting hyppo==0.1.3
  Using cached hyppo-0.1.3.tar.gz (38 kB)
Collecting POT>=0.7.0
  Using cached POT-0.7.0.tar.gz (189 kB)
    ERROR: Command errored out with exit status 1:
     command: 'l:\django projects\graspologic\venv_2\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\91968\\AppData\\Local\\Temp\
\pip-install-y3gg2s1x\\pot_efe24e61d57c4a02a7c021a79c05815c\\setup.py'"'"'; __file__='"'"'C:\\Users\\91968\\AppData\\Local\\Temp\\pip-install-y3gg2s1x\\pot_efe24e61d57c4
a02a7c021a79c05815c\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, _
_file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\91968\AppData\Local\Temp\pip-pip-egg-info-onfulp2f'
         cwd: C:\Users\91968\AppData\Local\Temp\pip-install-y3gg2s1x\pot_efe24e61d57c4a02a7c021a79c05815c\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\91968\AppData\Local\Temp\pip-install-y3gg2s1x\pot_efe24e61d57c4a02a7c021a79c05815c\setup.py", line 8, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
- Manually Installed Cython and Numpy using pip with the latest version.
- Ran make test, All the tests passed successfully with few warnings.
>
(venv_2) L:\Django projects\graspologic>make test
pytest tests
========================================================================= test session starts ==========================================================================
platform win32 -- Python 3.9.0, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: L:\Django projects\graspologic, configfile: pytest.ini
plugins: cov-2.11.1
collected 357 items                                                                                                                                                     

tests\test_base_embed.py ......                                                                                                                                   [  1%]
tests\test_datasets.py ...                                                                                                                                        [  2%]
tests\test_io.py ...........                                                                                                                                      [  5%]
tests\test_latentdistributiontest.py ..............                                                                                                               [  9%]
tests\test_latentpositiontest.py .........                                                                                                                        [ 12%]
tests\test_mase.py ....                                                                                                                                           [ 13%]
tests\test_match.py ........                                                                                                                                      [ 15%]
tests\test_mds.py ...                                                                                                                                             [ 16%]
tests\test_models.py ...........................                                                                                                                  [ 23%]
tests\test_mug2vec.py ..                                                                                                                                          [ 24%]
tests\test_n2v.py ......                                                                                                                                          [ 26%]
tests\test_omni.py ........                                                                                                                                       [ 28%]
tests\test_orthogonal_procrustes.py ...                                                                                                                           [ 29%]
tests\test_plot.py ................                                                                                                                               [ 33%]
tests\test_plot_matrix.py ....                                                                                                                                    [ 34%]
tests\test_ptr.py .............                                                                                                                                   [ 38%]
tests\test_rdpg_corr.py ....                                                                                                                                      [ 39%]
tests\test_seedless_procrustes.py ....                                                                                                                            [ 40%]
tests\test_select_dimension.py .....                                                                                                                              [ 42%]
tests\test_sg.py .......                                                                                                                                          [ 43%]
tests\test_sign_flips.py ....                                                                                                                                     [ 45%]
tests\test_sims.py ..................................                                                                                                             [ 54%]
tests\test_sims_corr.py ......                                                                                                                                    [ 56%]
tests\test_spectral_embed.py ...........................                                                                                                          [ 63%]
tests\test_spectral_nomination.py .................                                                                                                               [ 68%]
tests\test_svd.py ..                                                                                                                                              [ 69%]
tests\test_utils.py .................................                                                                                                             [ 78%]
tests\test_vertex_nomination_via_SGM.py ..                                                                                                                        [ 78%]
tests\cluster\test_autogmm.py .............                                                                                                                       [ 82%]
tests\cluster\test_divisive_cluster.py ........                                                                                                                   [ 84%]
tests\cluster\test_gclust.py .......                                                                                                                              [ 86%]
tests\cluster\test_kclust.py ....                                                                                                                                 [ 87%]
tests\embed\test_n2v.py .                                                                                                                                         [ 88%]
tests\layouts\test_auto.py .                                                                                                                                      [ 88%]
tests\layouts\nooverlap\test_grid.py ....                                                                                                                         [ 89%]
tests\layouts\nooverlap\test_grid_cell_creation.py ...                                                                                                            [ 90%]
tests\layouts\nooverlap\test_nooverlap.py ..............                                                                                                          [ 94%]
tests\layouts\nooverlap\test_overlap_check.py .....                                                                                                               [ 95%]
tests\partition\test_leiden.py .............                                                                                                                      [ 99%]
tests\partition\test_modularity.py ..                                                                                                                             [100%]

=========================================================================== warnings summary ===========================================================================
venv_2\lib\site-packages\sklearn\base.py:848
venv_2\lib\site-packages\sklearn\base.py:848
venv_2\lib\site-packages\sklearn\base.py:848
venv_2\lib\site-packages\sklearn\base.py:848
venv_2\lib\site-packages\sklearn\base.py:848
venv_2\lib\site-packages\sklearn\base.py:848
  l:\django projects\graspologic\venv_2\lib\site-packages\sklearn\base.py:848: FutureWarning: _pairwise was deprecated in 0.24 and will be removed in 1.1 (renaming of 0.
26). Set the estimator tags of your estimator instead
    warnings.warn(

venv_2\lib\site-packages\scipy\stats\_distn_infrastructure.py:1877: 11 warnings
  l:\django projects\graspologic\venv_2\lib\site-packages\scipy\stats\_distn_infrastructure.py:1877: RuntimeWarning: invalid value encountered in true_divide
    x = np.asarray((x - loc)/scale, dtype=dtyp)

tests\test_spectral_nomination.py:11
  L:\Django projects\graspologic\tests\test_spectral_nomination.py:11: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning,
 use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the prec
ision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    adj = np.array(sbm(3 * [n_verts], p), dtype=np.int)

tests\test_spectral_nomination.py:147
  L:\Django projects\graspologic\tests\test_spectral_nomination.py:147: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning
, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the pre
cision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    np.arange(n_verts - 1, dtype=np.int),

tests\test_spectral_nomination.py:163
  L:\Django projects\graspologic\tests\test_spectral_nomination.py:163: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning
, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the pre
cision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    np.arange(n_verts - 1, dtype=np.int),

tests/test_datasets.py: 32 warnings
tests/test_io.py: 8 warnings
  L:\Django projects\graspologic\graspologic\utils\utils.py:153: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, u
se `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    out = [nx.to_numpy_array(G, nodelist=vertices, dtype=np.float) for G in graphs]

tests/test_io.py::TestImportGraph::test_graphin
tests/test_latentdistributiontest.py::TestLatentDistributionTest::test_passing_networkx
tests/test_latentdistributiontest.py::TestLatentDistributionTest::test_passing_networkx
tests/test_spectral_embed.py::TestAdjacencySpectralEmbed::test_transform_networkx
tests/test_spectral_embed.py::TestAdjacencySpectralEmbed::test_transform_networkx
tests/test_utils.py::TestInput::test_graphin
  L:\Django projects\graspologic\graspologic\utils\utils.py:45: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, us
e `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    out = nx.to_numpy_array(graph, nodelist=sorted(graph.nodes), dtype=np.float)

tests/test_latentdistributiontest.py: 18 warnings
  l:\django projects\graspologic\venv_2\lib\site-packages\hyppo\_utils.py:67: RuntimeWarning: The number of replications is low (under 1000), and p-value calculations ma
y be unreliable. Use the p-value result, with caution!
    warnings.warn(msg, RuntimeWarning)

tests/test_latentdistributiontest.py::TestLatentDistributionTest::test_distances_and_kernels
tests/test_latentdistributiontest.py::TestLatentDistributionTest::test_pooled
  l:\django projects\graspologic\venv_2\lib\site-packages\scipy\stats\_multivariate.py:666: RuntimeWarning: covariance is not positive-semidefinite.
    out = random_state.multivariate_normal(mean, cov, size)

tests/test_n2v.py: 1424 warnings
tests/embed/test_n2v.py: 110 warnings
  L:\Django projects\graspologic\graspologic\embed\n2v.py:476: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `in
t` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. I
f you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    sampled_probabilities = np.zeros(number_of_outcomes, dtype=np.int)

tests/test_n2v.py::Node2VecEmbedTest::test_node2vec_embedding_barbell_graph_correct_shape_is_returned
  l:\django projects\graspologic\venv_2\lib\site-packages\scipy\sparse\sparsetools.py:21: DeprecationWarning: `scipy.sparse.sparsetools` is deprecated!
  scipy.sparse.sparsetools is a private module for scipy.sparse, and should not be used.
    _deprecated()

tests/test_omni.py::test_invalid_inputs
  l:\django projects\graspologic\venv_2\lib\site-packages\numpy\core\_asarray.py:171: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which
is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating
 the ndarray.
    return array(a, dtype, copy=False, order=order, subok=True)

tests/test_plot.py: 12 warnings
  L:\Django projects\graspologic\graspologic\plot\plot.py:721: RuntimeWarning: divide by zero encountered in double_scalars
    angle = np.arctan(u[1] / u[0])

tests/test_plot.py::test_pairplot_with_gmm_outputs_type_spherical
  L:\Django projects\graspologic\graspologic\plot\plot.py:881: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matp
lotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
    fig, axes = plt.subplots(dimensions, dimensions, figsize=figsize, squeeze=False)

tests/test_seedless_procrustes.py: 802 warnings
  l:\django projects\graspologic\venv_2\lib\site-packages\ot\bregman.py:363: RuntimeWarning: divide by zero encountered in true_divide
    v = np.divide(b, KtransposeU)

tests/test_seedless_procrustes.py::TestSeedlessProcrustes::test_aligning_datasets
tests/test_seedless_procrustes.py::TestSeedlessProcrustes::test_aligning_datasets
  l:\django projects\graspologic\venv_2\lib\site-packages\ot\bregman.py:363: RuntimeWarning: overflow encountered in true_divide
    v = np.divide(b, KtransposeU)

tests/test_sims.py::Test_MMSBM::test_bad_inputs
tests/test_sims.py::Test_MMSBM::test_bad_inputs
tests/test_sims.py::Test_MMSBM::test_bad_inputs
  l:\django projects\graspologic\venv_2\lib\site-packages\sklearn\utils\validation.py:63: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if
 dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
    return f(*args, **kwargs)

tests/test_spectral_nomination.py::TestSpectralVertexNominatorOutputs::test_seed_inputs
  L:\Django projects\graspologic\tests\test_spectral_nomination.py:29: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning,
 use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the prec
ision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    _nominate(adj, np.zeros((5, 5, 5), dtype=np.int))

tests/test_spectral_nomination.py: 16 warnings
  L:\Django projects\graspologic\graspologic\nominate\spectralVN.py:101: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warnin
g, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the pr
ecision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    elif not np.issubdtype(X.dtype, np.int):

tests/test_spectral_nomination.py::TestSpectralVertexNominatorOutputs::test_seed_inputs
  L:\Django projects\graspologic\tests\test_spectral_nomination.py:34: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning,
 use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the prec
ision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    _nominate(adj, np.zeros((1, 50), dtype=np.int))

tests/test_spectral_nomination.py::TestSpectralVertexNominatorOutputs::test_X_inputs
  L:\Django projects\graspologic\tests\test_spectral_nomination.py:54: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning,
 use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the prec
ision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    _nominate(np.random.random((10, 10)), np.zeros(3, dtype=np.int))

tests/test_spectral_nomination.py::TestSpectralVertexNominatorOutputs::test_X_inputs
tests/test_spectral_nomination.py::TestSpectralVertexNominatorOutputs::test_X_inputs
  L:\Django projects\graspologic\tests\test_spectral_nomination.py:59: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning,
 use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the prec
ision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    _nominate(np.zeros((5, 5, 5), dtype=np.int), np.zeros(3, dtype=np.int))

tests/test_spectral_nomination.py::TestSpectralVertexNominatorOutputs::test_X_inputs
  L:\Django projects\graspologic\tests\test_spectral_nomination.py:49: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning,
 use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the prec
ision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    _nominate([[0] * 10] * 10, np.zeros(3, dtype=np.int))

tests/test_spectral_nomination.py::TestSpectralVertexNominatorOutputs::test_X_inputs
tests/test_spectral_nomination.py::TestSpectralVertexNominatorOutputs::test_X_inputs
  L:\Django projects\graspologic\tests\test_spectral_nomination.py:67: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning,
 use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the prec
ision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    np.zeros((10, 20), dtype=np.int), np.zeros(3, dtype=np.int), nominator=svn

tests/test_spectral_nomination.py::TestSpectralVertexNominatorOutputs::test_X_inputs
tests/test_spectral_nomination.py::TestSpectralVertexNominatorOutputs::test_X_inputs
  L:\Django projects\graspologic\tests\test_spectral_nomination.py:74: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning,
 use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the prec
ision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    _nominate(np.zeros((3, 4), dtype=np.int), np.zeros(3, dtype=np.int))

tests/test_spectral_nomination.py: 12 warnings
  L:\Django projects\graspologic\graspologic\nominate\spectralVN.py:222: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warnin
g, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the pr
ecision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    y_vec = self.embedding_[y.astype(np.int)]

tests/test_spectral_nomination.py: 12 warnings
  L:\Django projects\graspologic\graspologic\nominate\spectralVN.py:227: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warnin
g, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the pr
ecision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    return nomination_list.T.astype(np.int), distance_matrix.T

tests/test_spectral_nomination.py::TestSpectralVertexNominatorOutputs::test_pre_embedded[seed0]
tests/test_spectral_nomination.py::TestSpectralVertexNominatorOutputs::test_pre_embedded[seed1]
tests/test_spectral_nomination.py::TestSpectralVertexNominatorOutputs::test_pre_embedded[seed2]
  L:\Django projects\graspologic\graspologic\nominate\spectralVN.py:99: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this war
ning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    if not np.issubdtype(X.dtype, np.float):

tests/test_svd.py::test_outputs
  L:\Django projects\graspologic\tests\test_svd.py:39: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float`
 by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    A = np.random.binomial(1, P).astype(np.float)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================================================ 357 passed, 2496 warnings in 597.16s (0:09:57) ============================================================

- Didn't run into any issue regarding graspologic-native.
- Also, I guess I have to build the tutorials now? how do I get started with that?
- Regarding 3.10, since numba doesn't yet support 3.10.. do we still have to check compliance for that?

**Comment by loftusa** [comment]
@dwaynepryce Do you know how he can build the tutorials? I'm still a little unfamiliar with the current build setup under the hood...

**Comment by dwaynepryce** [comment]
from graspologic repo root:
`make tutorials`

If you're on windows and don't have make, just call the command it uses in there 

If you ever want to know how we build our software, you can look at that root level Makefile and/or the github actions file in .github/workflows/build.yml iirc

**Comment by madlad33** [comment]
@dwaynepryce I have installed make on windows and ran make tutorials, the build succeeded. 

(venv_2) L:\Django projects\graspologic>make tutorials
sphinx-build -W -a docs/tutorials/ docs/tutorials/_build/html
Running Sphinx v3.5.4
loading intersphinx inventory from https://anytree.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://hyppo.neurodata.io/objects.inv...
loading intersphinx inventory from https://matplotlib.org/objects.inv...
loading intersphinx inventory from https://networkx.org/documentation/stable/objects.inv...
loading intersphinx inventory from https://numpy.org/doc/stable/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/scipy/reference/objects.inv...
loading intersphinx inventory from https://seaborn.pydata.org/objects.inv...
loading intersphinx inventory from https://scikit-learn.org/dev/objects.inv...
building [mo]: all of 0 po files
building [html]: all source files
updating environment: [new config] 29 added, 0 changed, 0 removed
reading sources... [100%] vertex_nomination/SpectralVertexNomination
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] vertex_nomination/SpectralVertexNomination
generating indices... genindex done
copying notebooks ... [100%] vertex_nomination/SpectralVertexNomination.ipynb
writing additional pages... search done
copying images... [100%] _build/html/.doctrees/nbsphinx/vertex_nomination_SpectralVertexNomination_7_0.png
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in docs\tutorials\_build\html.

**Comment by daxpryce** [comment]
Closing this issue because we're there with 3.9 #889 and looking into it with #869
