### ISSUE TITLE
Avoid `for` loops in MASE (and maybe other places)

### ISSUE THREAD

**Issue by loftusa** [microsoft/graspologic#780]
This test passes:

```
from <graspologic's tests/test_mase.py module> import make_train_undirected

def test_scores_equal():
    """
    This shows a better way of calculating scores, proving that the list comprehension
    and matrix multiplication method produce the same result.
    """
    A = np.asarray(make_train_undirected())
    mase = MultipleASE().fit(A)
    Uhat = mase.latent_left_

    scores = np.asarray([Uhat.T @ graph @ Uhat for graph in list(A)])
    scores_ = Uhat.T @ A @ Uhat

    assert np.array_equal(scores, scores_)
```

Uhat is a 2D array, A is a 3D array. MASE currently calculates score matrices in a `for` loop, the way that `scores` is calculated -- but numpy lets you do the whole thing in a vectorized way, where `Uhat.T @ A @ Uhat` is equivalent to calling `Uhat.T @ graph @ Uhat` for each graph on the z-axis of `A`, the way that `scores_` is calculated.

Numpy vectorization usually results in a multiple-orders-of-magnitude speed increase over using for-loops, so it's probably worth changing this (and scouring for other places in the codebase where we use for-loops when we could use numpy vectorization instead)

**Comment by loftusa** [comment]
I added the `good first issue` label because it's pretty much just:
1. replace for-loop with numpy matrix multiplication
2. write a test to make sure the output is the same as it was when it was a for-loop

**Comment by rajpratyush** [comment]
@loftusa Shall i go for it

**Comment by loftusa** [comment]
> @loftusa Shall i go for it

Sure, but I'd finish up #753 first

**Comment by j1c** [comment]
@loftusa This only works if the input graphs is already a 3d array, which is what you did in the example. The for loop was used to deal with cases where the input is a list, and we dont have to explicitly create a copy of the input data as a 3d-array if the input is a list. Creating this array can be very costly since numpy arrays require contiguous blocks of memory, and will require double the amount of memory since stacking arrays will always copy the data. It doesn't scale well as the size of input graphs increase and you dont want to use a 3d array when your graphs are large. The whole multi-graph stuff was written in the way it is so that we dont create unnecessary arrays unless we _have_ to.

I agree with the sentiment that matrix multiplication code looks better and _can_ be faster, but in this case, it ignores the fact that the input can be a list. I dont think this is a change we want, at least for this specific line of code.

**Comment by shruthi223** [comment]
Hi! I'm new here, could you assign me this?

**Comment by murari2401** [comment]
> I added the `good first issue` label because it's pretty much just:
> 
> 1. replace for-loop with numpy matrix multiplication
> 2. write a test to make sure the output is the same as it was when it was a for-loop
> 3. find other places in graspologic library where we can do this (e.g., probably with omni, and other multigraph algorithms)

Hi, Can you assign me this, I have just started open source contribution if you can assign me this will be helpful... 
Thank you

**Comment by vishaljha2121** [comment]
Hello @loftusa , I am starting to work on this issue as anyone has not been assigned to it. Please let me know if someone has already fixed the issue.

**Comment by loftusa** [comment]
@shruthi223
@murari2401 
@vishaljha2121 

Hey all. Thanks for your interest! For this specific issue, see what @j1c wrote - we may not want this. I encourage everyone to check out other issues!
